"use client";

import localFont from "next/font/local";
import "./globals.css";
import "./custom.css";
import Nav from "@/component/Nav";
import Footer from "@/component/Footer";
import { useEffect } from "react";
import { enableSmoothScroll } from "@/component/SmoothScrollWrapper";
import LenisSmoothScroll from "@/component/LenisSmoothScroll";

const testSignifier = localFont({
  src: [
    {
      path: "../../public/fonts/signifier-font-family-1761450363-0/TestSignifier-RegularItalic-BF663d8462d189e.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/signifier-font-family-1761450363-0/TestSignifier-BoldItalic-BF663d84627c436.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-testsignifier",
});

const ppNeueMontreal = localFont({
  src: [
    {
      path: "../../public/fonts/pp-neue-montreal-cdnfonts/ppneuemontreal-medium.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/pp-neue-montreal-cdnfonts/ppneuemontreal-bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-ppneuemontreal",
});

// export const metadata = {
//   title: "Vantage Point Acupuncture",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    enableSmoothScroll();
  }, []);

  return (
    <html lang="en">
      <body
        className={`${testSignifier.variable} ${ppNeueMontreal.variable} antialiased flex flex-col min-h-screen`}
      >
        <LenisSmoothScroll/>
        {/* Header at the top */}
        <Nav />

        {/* Main content grows to fill space */}
        <main className="grow">{children}</main>

        {/* Footer always at bottom */}
        <Footer />
      </body>
    </html>
  );
}
